# Generated by Django 5.0.4 on 2024-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('past_simple', models.CharField(max_length=100)),
                ('past_participle', models.CharField(max_length=100)),
            ],
        ),
    ]
