# Generated by Django 4.2.13 on 2024-06-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbapp', '0002_alter_irregularverb_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='irregularverb',
            name='memory_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='irregularverb',
            name='base',
            field=models.CharField(max_length=100, verbose_name='Infinitiv'),
        ),
        migrations.AlterField(
            model_name='irregularverb',
            name='past_participle',
            field=models.CharField(max_length=100, verbose_name='Partizip II'),
        ),
        migrations.AlterField(
            model_name='irregularverb',
            name='past_simple',
            field=models.CharField(max_length=100, verbose_name='Präteritum'),
        ),
    ]
