# Generated by Django 4.2.13 on 2024-06-22 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verbapp', '0003_irregularverb_memory_score_alter_irregularverb_base_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='irregularverb',
            name='memory_score',
        ),
        migrations.CreateModel(
            name='UserVerbStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbapp.irregularverb')),
            ],
            options={
                'unique_together': {('user', 'verb')},
            },
        ),
    ]
